//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFoods
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Purchases
    {
        public int id { get; set; }
        public short Vendor_id_fk { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_vendor tbl_vendor { get; set; }
    }
}
