//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFoods
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Vehicle()
        {
            this.tbl_Sales = new HashSet<tbl_Sales>();
            this.tbl_vehicleExp = new HashSet<tbl_vehicleExp>();
        }
    
        public short Id { get; set; }
        public string Vehicle_number { get; set; }
        public System.DateTime Fitness_date { get; set; }
        public System.DateTime Insurance_date { get; set; }
        public System.DateTime MH_tax { get; set; }
        public System.DateTime AI_tax { get; set; }
        public System.DateTime Permit { get; set; }
        public System.DateTime PUC { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sales> tbl_Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vehicleExp> tbl_vehicleExp { get; set; }
    }
}
