//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFoods
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_salary
    {
        public int id { get; set; }
        public short Emp_id_fk { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
