//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFoods
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleDetails
    {
        public int id { get; set; }
        public int sales_id_fk { get; set; }
        public int Product_id_fk { get; set; }
        public short Product_qty { get; set; }
        public decimal Product_total_price { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tbl_Products tbl_Products { get; set; }
        public virtual tbl_Sales tbl_Sales { get; set; }
    }
}
