//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFoods
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sales()
        {
            this.tbl_SaleDetails = new HashSet<tbl_SaleDetails>();
        }
    
        public int id { get; set; }
        public System.DateTime Date_of_purchase { get; set; }
        public short Vehicle_no { get; set; }
        public string Transporter_name { get; set; }
        public decimal Total_bill { get; set; }
        public decimal Amount_due { get; set; }
        public string Payment_status_comments { get; set; }
        public int customer_id_fk { get; set; }
        public bool isDelete { get; set; }
        public Nullable<bool> isGST { get; set; }
    
        public virtual tbl_CustomerDetails tbl_CustomerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SaleDetails> tbl_SaleDetails { get; set; }
        public virtual tbl_Vehicle tbl_Vehicle { get; set; }
    }
}
